services:

  postgres:
    image: postgres:17
    container_name: mini_uber_eats_postgres
    environment:
      POSTGRES_DB: uber_eats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kira@004
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mini_uber_eats_redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mini-uber-eats-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: