# Generated by Django 6.1.1 on 2026-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_outboxevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('ORDER_READY', 'Order Ready')], max_length=100),
        ),
    ]
